name: 'Robot Framework RoboCop'
description: 'Run Robocop'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  max-warnings:
    description: 'Warning Max number'
    required: true   
    
  path:
    description: 'Path'
    required: false    
    
  argumentfile:
    description: 'Arguments File Configuration'
    required: true
  
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.max-warnings }}
    - ${{ inputs.path }}
    - ${{ argumentfile }} 
